Duel.LoadScript("proc_fusion.lua")
Duel.LoadScript("proc_link.lua")
Duel.LoadScript("proc_ritual.lua")
Duel.LoadScript("proc_synchro.lua")
Duel.LoadScript("proc_xyz.lua")
Duel.LoadScript("convert-from-core-constant.lua")
Duel.LoadScript("convert-from-core-proc_fusion.lua")
Duel.LoadScript("convert-from-core-proc_link.lua")
Duel.LoadScript("convert-from-core-proc_pendulum.lua")
if IREDO_COMES_TRUE==nil then
	Duel.LoadScript("convert-from-core-proc_procs.lua")
end
Duel.LoadScript("convert-from-core-proc_ritual.lua")
Duel.LoadScript("convert-from-core-proc_synchro.lua")
Duel.LoadScript("convert-from-core-proc_union.lua")
Duel.LoadScript("convert-from-core-proc_xyz.lua")
Duel.LoadScript("convert-from-core-utility.lua")