Duel.LoadScript("expansions/script/proc_fusion.lua")
Duel.LoadScript("expansions/script/proc_link.lua")
Duel.LoadScript("expansions/script/proc_ritual.lua")
Duel.LoadScript("expansions/script/proc_synchro.lua")
Duel.LoadScript("expansions/script/proc_xyz.lua")
Duel.LoadScript("expansions/convert-from-core-constant.lua")
Duel.LoadScript("expansions/convert-from-core-proc_fusion.lua")
Duel.LoadScript("expansions/convert-from-core-proc_link.lua")
Duel.LoadScript("expansions/convert-from-core-proc_pendulum.lua")
if IREDO_COMES_TRUE==nil then
	Duel.LoadScript("expansions/convert-from-core-proc_procs.lua")
end
Duel.LoadScript("expansions/convert-from-core-proc_ritual.lua")
Duel.LoadScript("expansions/convert-from-core-proc_synchro.lua")
Duel.LoadScript("expansions/convert-from-core-proc_xyz.lua")
Duel.LoadScript("expansions/convert-from-core-utility.lua")