--종언패룡 "룰러" 카타클리즘
local s,id=GetID()
function s.initial_effect(c)
	c:EnableReviveLimit()
	Fusion.AddProcMix(c,false,false,s.pfil1,s.pfil2)
	local e1=Effect.CreateEffect(c)
	e1:SetDescription(aux.Stringid(id,0))
	e1:SetCategory(CATEGORY_DESTROY)
	e1:SetType(EFFECT_TYPE_QUICK_O)
	e1:SetCode(EVENT_FREE_CHAIN)
	e1:SetProperty(EFFECT_FLAG_NO_TURN_RESET)
	e1:SetHintTiming(0,TIMINGS_CHECK_MONSTER_E)
	e1:SetRange(LOCATION_MZONE)
	e1:SetCountLimit(1)
	e1:SetTarget(s.tar1)
	e1:SetOperation(s.op1)
	c:RegisterEffect(e1)
	local e2=Effect.CreateEffect(c)
	e2:SetDescription(aux.Stringid(id,1))
	e2:SetCategory(CATEGORY_TOHAND+CATEGORY_SPECIAL_SUMMON)
	e2:SetType(EFFECT_TYPE_IGNITION)
	e2:SetProperty(EFFECT_FLAG_CARD_TARGET)
	e2:SetRange(LOCATION_MZONE)
	e2:SetCountLimit(1)
	e2:SetTarget(s.tar2)
	e2:SetOperation(s.op2)
	c:RegisterEffect(e2)
end
function s.pfil1(c)
	return c:IsCode(4538826) or c:IsCode(82301904)
end
function s.pfil2(c)
	return c:IsCode(4538826) or c:IsCode(12782649) or c:IsCode(12782650) or c:IsCode(12782651) or c:IsCode(12782652)
end
function s.tar1(e,tp,eg,ep,ev,re,r,rp,chk)
	local g=Duel.GetMatchingGroup(nil,tp,0,LOCATION_ONFIELD,nil)
	if chk==0 then
		return #g>0
	end
	Duel.SetOperationInfo(0,CATEGORY_DESTROY,g,#g,0,0)
end
function s.op1(e,tp,eg,ep,ev,re,r,rp)
	local g=Duel.GetMatchingGroup(nil,tp,0,LOCATION_ONFIELD,nil)
	Duel.Destroy(g,REASON_EFFECT)
end
function s.tfil2(c,e,tp)
	return c:IsAbleToHand() and (c:IsCode(4538826)
		or c:IsCode(12782649)
		or c:IsCode(12782650)
		or c:IsCode(12782651)
		or c:IsCode(12782652)
		or c:IsCode(82301904)
		) and c:IsCanBeSpecialSummoned(e,0,tp,true,true) and c:IsFaceup()
end
function s.tar2(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then
		return Duel.IsExistingTarget(s.tfil2,tp,LOCATION_GRAVE+LOCATION_REMOVED,0,1,nil,e,tp)
			and Duel.GetLocationCount(tp,LOCATION_MZONE)>0
	end
	Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_ATOHAND)
	local g=Duel.SelectTarget(tp,s.tfil2,tp,LOCATION_GRAVE+LOCATION_REMOVED,0,1,1,nil,e,tp)
	Duel.SetOperationInfo(0,CATEGORY_TOHAND,g,1,0,0)
	Duel.SetOperationInfo(0,CATEGORY_SPECIAL_SUMMON,nil,1,tp,LOCATION_HAND)
end
function s.op2(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local tc=Duel.GetFirstTarget()
	if tc:IsRelateToEffect(e) then
		Duel.SendtoHand(tc,nil,REASON_EFFECT)
		Duel.ConfirmCards(1-tp,tc)
		if Duel.SpecialSummon(tc,0,tp,tp,true,false,POS_FACEUP)>0 then
			if tc:GetOriginalCodeRule()==4538826 then
				local e4=Effect.CreateEffect(tc)
				e4:SetDescription(aux.Stringid(4538826,1))
				e4:SetCategory(CATEGORY_TOGRAVE+CATEGORY_DAMAGE)
				e4:SetType(EFFECT_TYPE_QUICK_O)
				e4:SetCode(EVENT_FREE_CHAIN)
				e4:SetRange(LOCATION_MZONE)
				e4:SetReset(RESET_EVENT+RESETS_STANDARD)
				e4:SetCountLimit(1)
				e4:SetCondition(function(e)
					return not e:GetHandler():IsStatus(STATUS_CHAINING)
				end)
				e4:SetCost(c4538826.gycost)
				e4:SetTarget(c4538826.gytg)
				e4:SetOperation(c4538826.gyop)
				tc:RegisterEffect(e4)
			elseif tc:GetOriginalCodeRule()==82301904 then
				local e3=Effect.CreateEffect(tc)
				e3:SetDescription(aux.Stringid(82301904,1))
				e3:SetCategory(CATEGORY_TOGRAVE+CATEGORY_DAMAGE)
				e3:SetType(EFFECT_TYPE_QUICK_O)
				e3:SetCode(EVENT_FREE_CHAIN)
				e3:SetRange(LOCATION_MZONE)
				e3:SetReset(RESET_EVENT+RESETS_STANDARD)
				e3:SetCountLimit(1)
				e3:SetCondition(function(e)
					return not e:GetHandler():IsStatus(STATUS_CHAINING)
				end)
				e3:SetCost(c82301904.sgcost)
				e3:SetTarget(c82301904.sgtg)
				e3:SetOperation(c82301904.sgop)
				tc:RegisterEffect(e3)
			elseif tc:GetOriginalCodeRule()==12782649 then
				local e2=Effect.CreateEffect(c)
				e2:SetType(EFFECT_TYPE_QUICK_O)
				e2:SetCode(EVENT_FREE_CHAIN)
				e2:SetRange(LOCATION_MZONE)
				e2:SetCategory(CATEGORY_DESTROY)
				e2:SetReset(RESET_EVENT+RESETS_STANDARD)
				e2:SetCountLimit(1,{12782649,1})
				e2:SetTarget(c12782649.tar2)
				e2:SetOperation(c12782649.op2)
				c:RegisterEffect(e2)
			elseif tc:GetOriginalCodeRule()==12782650 then
				local e2=Effect.CreateEffect(c)
				e2:SetType(EFFECT_TYPE_QUICK_O)
				e2:SetCode(EVENT_FREE_CHAIN)
				e2:SetRange(LOCATION_MZONE)
				e2:SetCategory(CATEGORY_DESTROY)
				e2:SetReset(RESET_EVENT+RESETS_STANDARD)
				e2:SetCountLimit(1,{12782650,1})
				e2:SetTarget(c12782650.tar2)
				e2:SetOperation(c12782650.op2)
				c:RegisterEffect(e2)
			elseif tc:GetOriginalCodeRule()==12782651 then
				local e2=Effect.CreateEffect(c)
				e2:SetType(EFFECT_TYPE_QUICK_O)
				e2:SetCode(EVENT_FREE_CHAIN)
				e2:SetRange(LOCATION_MZONE)
				e2:SetCategory(CATEGORY_DESTROY)
				e2:SetReset(RESET_EVENT+RESETS_STANDARD)
				e2:SetCountLimit(1,{12782651,1})
				e2:SetTarget(c12782651.tar2)
				e2:SetOperation(c12782651.op2)
				c:RegisterEffect(e2)
			elseif tc:GetOriginalCodeRule()==12782652 then
				local e2=Effect.CreateEffect(c)
				e2:SetType(EFFECT_TYPE_QUICK_O)
				e2:SetCode(EVENT_FREE_CHAIN)
				e2:SetRange(LOCATION_MZONE)
				e2:SetCategory(CATEGORY_DISABLE)
				e2:SetReset(RESET_EVENT+RESETS_STANDARD)
				e2:SetCountLimit(1,{12782652,1})
				e2:SetTarget(c12782652.tar2)
				e2:SetOperation(c12782652.op2)
				c:RegisterEffect(e2)
			end
		end
	end
end