name: Script validity checker old
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  check-scripts-old:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Download checker
      run: |
        curl --retry 5 --connect-timeout 30 --location --remote-header-name --output ignis-test-bin.tar.gz https://github.com/ProjectIgnis/Checker/releases/download/1.1.1/ignis-test-bin.tar.gz
        tar xf ignis-test-bin.tar.gz
        cp ignis-test/script_syntax_check ignis-test/libocgcore.so .
        rm -rf ignis-test
    - name: Run checker
      run: |
        ./script_syntax_check .
